---
- hosts: mywebservers
  become: yes
  gather_facts: yes 
  tasks:
   - name: Installing Webserver Playbook on Ubuntu 
     apt: 
      name: "{{mywebpackonubuntu}}"
      state: present
   - name: Installing webserver Playbook on Redhat
     apt: 
      name: "{{mywebpackonRedhat}}"
      state: started