- name: Downloading tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz 
    force_basic_auth: yes

- name: Create a directory
  file: 
    path: /opt/tomcat
    state: directory

- name: Extract the tar file.
  command: 
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
    # To execute only one time tar file we provide IDEMPOTENTS by create command.
    creates: /opt/tomcat/NOTICE