---
# tasks file for mytomcatrole

- include_tasks : update.yml
- include_tasks : user.yml
- include_tasks : download.yml
- include_tasks : permissions.yml
- include_tasks : ConfiguringAdminUsers.yml
- include_tasks : tomcatstartservice.yml
- include_tasks : tomcatstart.yml